export const MAJORS = [
  'Accounting',
  'Aerospace Engineering',
  'African American Studies',
  'Agriculture',
  'Animal Science',
  'Anthropology',
  'Architecture',
  'Art & Design',
  'Biochemistry',
  'Biology',
  'Biomedical Engineering',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Communications',
  'Computer Engineering',
  'Computer Science',
  'Criminal Justice',
  'Data Science',
  'Dental Hygiene',
  'Economics',
  'Education',
  'Electrical Engineering',
  'English',
  'Environmental Design',
  'Environmental Science',
  'Exercise Science',
  'Film & Media Studies',
  'Finance',
  'Foreign Languages',
  'Graphic Design',
  'Health Sciences',
  'History',
  'Hospitality Management',
  'Human Resources',
  'Industrial Engineering',
  'Information Systems',
  'Information Technology',
  'International Relations',
  'Journalism',
  'Kinesiology',
  'Law / Pre-Law',
  'Liberal Arts',
  'Linguistics',
  'Management',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Medicine / Pre-Med',
  'Music',
  'Nursing',
  'Nutrition',
  'Performing Arts',
  'Pharmacy / Pre-Pharmacy',
  'Philosophy',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Health',
  'Public Policy',
  'Real Estate',
  'Religious Studies',
  'Social Work',
  'Sociology',
  'Software Engineering',
  'Spanish',
  'Sports Management',
  'Statistics',
  'Supply Chain Management',
  'Theater',
  'Urban Planning',
  'Veterinary / Pre-Vet',
  'Undecided',
]
